FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY client/package*.json ./client/

# Install dependencies
RUN cd client && npm install

# Copy source code
COPY client ./client

WORKDIR /app/client

# Expose port
EXPOSE 5173

# Start in development mode
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
